from pymongo import MongoClient
import uuid

my_client = MongoClient("mongodb://root:1234@localhost:27017")
april = [{"uuid": str(uuid.uuid4()), "month": 3, "date": 30, "title": "골프공 ", "price": 27000, "category": "기타", "instrument": "hyundai"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 2, "title": "남서울cc", "price": 80000, "category": "기타", "instrument": "hyundai"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 5, "title": "카페", "price": 10000, "category": "약속", "instrument": "hyundai"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 5, "title": "맥도날드", "price": 14000, "category": "외식/배달", "instrument": "hyundai"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 10, "title": "남서울cc", "price": 60000, "category": "기타", "instrument": "hyundai"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 13, "title": "벨트", "price": 238000, "category": "쇼핑", "instrument": "hyundai"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 15, "title": "모자", "price": 39690, "category": "쇼핑", "instrument": "hyundai"},
{"uuid": str(uuid.uuid4()), "month": 3, "date": 31, "title": "교통비", "price": 10050, "category": "교통", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 3, "title": "넷플릭스", "price": 17000, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 15, "title": "오아시스", "price": 25137, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 17, "title": "앵거스", "price": 53480, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 17, "title": "비비고", "price": 21612, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 17, "title": "GS25", "price": 4140, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 19, "title": "마켓컬리", "price": 43700, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 19, "title": "세탁소", "price": 6000, "category": "생필품", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 19, "title": "GS슈퍼", "price": 3300, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 19, "title": "ESTA", "price": 17617, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 20, "title": "가스비", "price": 40830, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 20, "title": "비타민젤리", "price": 15810, "category": "의료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 22, "title": "바디워시", "price": 10980, "category": "생필품", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month": 3, "date": 30, "title": "오아시스", "price": 19999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 3, "date": 31, "title": "gs슈퍼", "price": 23940, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 1, "title": "경성꽈배기", "price": 8550, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 2, "title": "세탁소", "price": 12400, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 2, "title": "지코바", "price": 16500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 3, "title": "마켓컬리", "price": 21999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 3, "title": "쌀", "price": 27930, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 4, "title": "참치 ", "price": 10900, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 5, "title": "식자재마트", "price": 6580, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 6, "title": "편의점", "price": 6500, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 7, "title": "바이통타이", "price": 18600, "category": "약속", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 7, "title": "버거킹", "price": 15999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 7, "title": "오목눈이", "price": 22800, "category": "약속", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 8, "title": "헬로네이처", "price": 47999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 9, "title": "런던베이글뮤지엄", "price": 18700, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 9, "title": "진작", "price": 39900, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 9, "title": "하프커피", "price": 11700, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 9, "title": "탱크탑", "price": 9999, "category": "쇼핑", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 10, "title": "마켓컬리", "price": 19999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 10, "title": "후참", "price": 17999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 10, "title": "라티놀", "price": 18999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 11, "title": "방수매트", "price": 5999, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 12, "title": "형광등", "price": 11560, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 13, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 13, "title": "?", "price": 11700, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 13, "title": "클렌징워터", "price": 16900, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 14, "title": "오목눈이", "price": 15800, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 14, "title": "롯데리아", "price": 12999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 15, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 16, "title": "경성꽈배기", "price": 8500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 17, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 19, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 19, "title": "회덮밥", "price": 11700, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 20, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 22, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month": 4, "date": 22, "title": "피자", "price": 21760, "category": "외식/배달", "instrument": "shinhan"}]

hyundai=[{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":5,"title":"오렌지 티슈","price":17900,"category":"기타"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":8,"title":"루돌프 코","price":3820,"category":"기타"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":9,"title":"곤니치와봉주르","price":36343,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":9,"title":"골프장갑","price":28000,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":11,"title":"나랑드사이다","price":14000,"category":"식재료"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":13,"title":"골프옷(나이키)","price":292500,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":13,"title":"골프옷(핑)","price":252000,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":14,"title":"오목눈이","price":27000,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":15,"title":"마켓컬리","price":18999,"category":"식재료"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":16,"title":"하이마블","price":73000,"category":"식재료"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":16,"title":"감탄브라","price":52400,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":19,"title":"CGV 콜라","price":4900,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":19,"title":"카츠8","price":34000,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":20,"title":"화장솜","price":1500,"category":"기타"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":24,"title":"?","price":0,"category":"기타"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":25,"title":"IFC 주차비","price":9000,"category":"교통"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":12,"date":27,"title":"세제","price":11900,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":3,"title":"멀티탭","price":7500,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":7,"title":"혜림이선물","price":42000,"category":"기타"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":8,"title":"판교현백 밥","price":26800,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":16,"title":"흑백사장","price":70000,"category":"기타"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":18,"title":"오빠네 선물","price":32400,"category":"가족행사"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":21,"title":"아버님 소고기","price":240000,"category":"가족행사"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":22,"title":"세탁소","price":6000,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":23,"title":"키링","price":62360,"category":"기타"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":24,"title":"리바이포유","price":48100,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":24,"title":"어머님 소고기","price":162500,"category":"가족행사"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":25,"title":"고로","price":9500,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":27,"title":"카페소비","price":9000,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":27,"title":"세븐일레븐","price":11100,"category":"식재료"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":28,"title":"스시림","price":64000,"category":"가족행사"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":29,"title":"인도어","price":32000,"category":"기타"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":31,"title":"노량진 굴","price":12000,"category":"가족행사"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":1,"date":31,"title":"배스킨","price":22000,"category":"가족행사"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":5,"title":"골프장갑","price":28650,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":7,"title":"산부인과","price":34700,"category":"의료"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":7,"title":"산부인과","price":10500,"category":"의료"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":8,"title":"신선설렁탕","price":17000,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":9,"title":"산부인과","price":1300,"category":"의료"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":16,"title":"스타벅스","price":10000,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":16,"title":"핸드워시","price":19900,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":17,"title":"세탁소","price":6000,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":18,"title":"헤이그","price":35400,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":19,"title":"아웃백쿠폰","price":46450,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":19,"title":"테이블","price":19900,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":20,"title":"편의점","price":8200,"category":"식재료"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":23,"title":"굽네배달비","price":3000,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":24,"title":"마리떼","price":43100,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":28,"title":"베라 기프티콘","price":31000,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":2,"date":28,"title":"논픽션 시향","price":2500,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":1,"title":"오빠네 떡볶이","price":12000,"category":"외식/배달"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":2,"title":"드라이시트","price":10500,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":2,"title":"나무수저","price":17370,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":4,"title":"준오헤어","price":36000,"category":"기타"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":5,"title":"에르메스","price":610000,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":6,"title":"골프장갑","price":26290,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":7,"title":"사이다","price":31200,"category":"식재료"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":8,"title":"다이소","price":1000,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":9,"title":"유명골프클럽","price":34000,"category":"기타"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":9,"title":"쓰레기봉지","price":5000,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":11,"title":"세탁소","price":15150,"category":"생필품"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":14,"title":"시에","price":119000,"category":"쇼핑"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":15,"title":"편의점","price":4500,"category":"식재료"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":22,"title":"판다","price":23500,"category":"약속"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":22,"title":"사진전","price":24000,"category":"약속"},{"uuid": str(uuid.uuid4()), "instrument":"hyundai","month":3,"date":27,"title":"청기와타운","price":92000,"category":"외식/배달"}]
woori=[{"uuid": str(uuid.uuid4()), "month":12, "date": 1, "title": "홍콩반점", "price": 22000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 6, "title": "버거킹", "price": 11700, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 6, "title": "주차비", "price": 6500, "category": "교통", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 8, "title": "헬로네이처", "price": 41580, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 8, "title": "엽떡", "price": 23000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 8, "title": "오목눈이", "price": 18600, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 9, "title": "넷플릭스", "price": 10150, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 13, "title": "편의점", "price": 12500, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 13, "title": "세탁소", "price": 6000, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 14, "title": "마라탕", "price": 39000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 20, "title": "가스비", "price": 58920, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 21, "title": "GS 슈퍼", "price": 2180, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 26, "title": "유튜브", "price": 6083, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 27, "title": "관리비", "price": 110860, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 2, "title": "굽네치킨", "price": 12000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 4, "title": "스시소라", "price": 160000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 7, "title": "이디야", "price": 11000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 8, "title": "골프장", "price": 28000, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 8, "title": "피스피스", "price": 26800, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 8, "title": "요물커피", "price": 10400, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 9, "title": "넷플릭스", "price": 10150, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 13, "title": "영양제", "price": 17400, "category": "의료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 15, "title": "닭갈비", "price": 75000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 15, "title": "카페", "price": 11500, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 15, "title": "렌즈", "price": 58000, "category": "생필품", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 16, "title": "요기패스", "price": 900, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 20, "title": "가스비", "price": 100820, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 25, "title": "관리비", "price": 111530, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 26, "title": "유튜브", "price": 6083, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 3, "title": "커피빈", "price": 10200, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 4, "title": "루루 보험", "price": 467590, "category": "가족행사", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 5, "title": "라티놀", "price": 21100, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 9, "title": "넷플릭스", "price": 11900, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 21, "title": "가스비", "price": 99580, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 22, "title": "관리비", "price": 130090, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 26, "title": "유튜브", "price": 6083, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 26, "title": "연회비", "price": 15000, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 1, "title": "요기패스", "price": 4400, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 6, "title": "이탈리안클럽", "price": 94000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 6, "title": "밀리토피아 골프", "price": 33000, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 6, "title": "컨플릭트 커피", "price": 13000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 8, "title": "트랙패드", "price": 11470, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 9, "title": "넷플릭스", "price": 11900, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 18, "title": "세븐일레븐", "price": 6000, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 18, "title": "약국", "price": 3000, "category": "의료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 18, "title": "동사무소", "price": 600, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 21, "title": "가스비", "price": 73300, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 22, "title": "신속항원", "price": 5000, "category": "의료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 25, "title": "관리비", "price": 133770, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 25, "title": "바닐라시럽", "price": 10000, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 26, "title": "유튜브", "price": 6083, "category": "고지서", "instrument": "woori"}]

shinhan=[{"uuid": str(uuid.uuid4()), "month":12, "date": 4, "title": "헬로네이처", "price": 25999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 5, "title": "요기요", "price": 12500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 6, "title": "로아르", "price": 61999, "category": "쇼핑", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 6, "title": "올리브영", "price": 37990, "category": "화장품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 9, "title": "마켓컬리", "price": 27999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 11, "title": "호빵", "price": 8999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 12, "title": "고트델리", "price": 36500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 12, "title": "마켓컬리", "price": 20980, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 15, "title": "카카오쇼핑", "price": 6900, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 16, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 17, "title": "배스킨라빈스", "price": 10999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 18, "title": "써브웨이", "price": 16999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 19, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 20, "title": "KFC", "price": 19500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 20, "title": "롯데시티호텔", "price": 39999, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 21, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 21, "title": "배민", "price": 10999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 22, "title": "유플러스", "price": 38243, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 23, "title": "헬로네이처", "price": 49999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 24, "title": "묵은지", "price": 7999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 25, "title": "돈까스", "price": 11520, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 25, "title": "커피빈", "price": 6100, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 25, "title": "아메리칸트레일러", "price": 5490, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 27, "title": "나무수저", "price": 9960, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 27, "title": "마스크", "price": 11999, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 28, "title": "세탁소", "price": 4800, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 28, "title": "디퓨저", "price": 15999, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 29, "title": "마켓컬리", "price": 13999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 30, "title": "후참", "price": 16500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 31, "title": "헬로네이처", "price": 40999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 1, "title": "김밥+라볶이", "price": 22800, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 4, "title": "오아시스", "price": 20999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 6, "title": "스팸", "price": 16999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 12, "title": "오목눈이", "price": 11300, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 12, "title": "헬로네이처", "price": 39999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 12, "title": "바이통타이", "price": 10700, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 12, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 14, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 15, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 16, "title": "배스킨라빈스", "price": 10400, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 16, "title": "김밥 라볶이", "price": 12600, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 16, "title": "립밤", "price": 7230, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 17, "title": "마켓컬리", "price": 20999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 17, "title": "버거킹", "price": 10999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 18, "title": "족발", "price": 26999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 18, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 19, "title": "자동차세", "price": 300545, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 19, "title": "헬로네이처", "price": 40999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 19, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 20, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 21, "title": "유플러스", "price": 20246, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 21, "title": "블랑오브", "price": 35800, "category": "쇼핑", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 21, "title": "마켓컬리", "price": 22810, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 22, "title": "파리바게뜨", "price": 7600, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 22, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 25, "title": "햇반", "price": 20720, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 26, "title": "UVO", "price": 1590, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 28, "title": "롯데리아", "price": 10700, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 30, "title": "피자", "price": 20410, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 31, "title": "굽네 쿠폰", "price": 7999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 31, "title": "서울페이", "price": 108000, "category": "가족행사", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 1, "title": "물", "price": 6900, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 1, "title": "식혜", "price": 7990, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 1, "title": "KFC", "price": 18500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 2, "title": "식자재마트", "price": 8780, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 5, "title": "헬로네이처", "price": 50999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 6, "title": "GS슈퍼", "price": 4950, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 6, "title": "편의점", "price": 12000, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 8, "title": "생리대", "price": 5930, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 9, "title": "헬로네이처", "price": 40999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 9, "title": "마스크", "price": 10900, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 10, "title": "라티놀", "price": 16600, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 11, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 12, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 13, "title": "죽", "price": 9999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 13, "title": "물", "price": 6900, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 13, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 14, "title": "배스킨라빈스", "price": 14500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 14, "title": "현미", "price": 10999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 16, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 16, "title": "오아시스", "price": 23999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 16, "title": "연두", "price": 6980, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 18, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 18, "title": "헬로네이처", "price": 42940, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 18, "title": "핸드폰케이스", "price": 10500, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 22, "title": "시스맥스 서랍", "price": 14999, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 23, "title": "유플러스", "price": 3416, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 23, "title": "마켓컬리", "price": 19999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 23, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 25, "title": "배스킨라빈스", "price": 7500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 25, "title": "요기패스", "price": 4900, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 28, "title": "유보", "price": 9900, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 1, "title": "GS슈퍼", "price": 9800, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 1, "title": "헬로네이쳐", "price": 40999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 3, "title": "고무장갑", "price": 11500, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 3, "title": "나이키", "price": 6999, "category": "쇼핑", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 7, "title": "맥도날드", "price": 12500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 8, "title": "카멜커피", "price": 5500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 9, "title": "홍콩반점", "price": 22900, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 11, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 11, "title": "크리넥스", "price": 8999, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 11, "title": "편의점", "price": 4400, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 12, "title": "버거킹", "price": 11999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 12, "title": "헬로네이처", "price": 37568, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 13, "title": "투썸", "price": 11200, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 14, "title": "컬리", "price": 19999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 15, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 15, "title": "뿌링클", "price": 13999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 16, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 19, "title": "피자", "price": 19999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 19, "title": "물", "price": 11900, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 19, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 20, "title": "라티놀", "price": 18500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 21, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 22, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 22, "title": "라이크유 니트", "price": 39900, "category": "쇼핑", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 23, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 24, "title": "유플러스", "price": 14247, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 24, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 24, "title": "요기패스", "price": 4900, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 24, "title": "롯데리아", "price": 10999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 26, "title": "식자재마트", "price": 26620, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 26, "title": "마스크", "price": 10999, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 28, "title": "유보", "price": 9900, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 28, "title": "마켓컬리", "price": 20999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 29, "title": "투썸", "price": 6400, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 29, "title": "유보", "price": 8940, "category": "기타", "instrument": "shinhan"}]

data = [{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 5, "title": '오렌지 티슈', "price": 17900, "category": '기타'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 8, "title": '루돌프 코', "price": 3820, "category": '기타'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 9, "title": '곤니치와봉주르', "price": 36343, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 9, "title": '골프장갑', "price": 28000, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 11, "title": '나랑드사이다', "price": 14000, "category": '식재료'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 13, "title": '골프옷(나이키)', "price": 292500, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 13, "title": '골프옷(핑)', "price": 252000, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 14, "title": '오목눈이', "price": 27000, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 15, "title": '마켓컬리', "price": 18999, "category": '식재료'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 16, "title": '하이마블', "price": 73000, "category": '식재료'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 16, "title": '감탄브라', "price": 52400, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 19, "title": 'CGV 콜라', "price": 4900, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 19, "title": '카츠8', "price": 34000, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 20, "title": '화장솜', "price": 1500, "category": '기타'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 24, "title": '?', "price": 0, "category": '기타'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 25, "title": 'IFC 주차비', "price": 9000, "category": '교통'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 12, "date": 27, "title": '세제', "price": 11900, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 3, "title": '멀티탭', "price": 7500, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 7, "title": '혜림이선물', "price": 42000, "category": '기타'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 8, "title": '판교현백 밥', "price": 26800, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 16, "title": '흑백사장', "price": 70000, "category": '기타'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 18, "title": '오빠네 선물', "price": 32400, "category": '가족행사'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 21, "title": '아버님 소고기', "price": 240000, "category": '가족행사'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 22, "title": '세탁소', "price": 6000, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 23, "title": '키링', "price": 62360, "category": '기타'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 24, "title": '리바이포유', "price": 48100, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 24, "title": '어머님 소고기', "price": 162500, "category": '가족행사'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 25, "title": '고로', "price": 9500, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 27, "title": '카페소비', "price": 9000, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 27, "title": '세븐일레븐', "price": 11100, "category": '식재료'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 28, "title": '스시림', "price": 64000, "category": '가족행사'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 29, "title": '인도어', "price": 32000, "category": '기타'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 31, "title": '노량진 굴', "price": 12000, "category": '가족행사'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 1, "date": 31, "title": '배스킨', "price": 22000, "category": '가족행사'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 5, "title": '골프장갑', "price": 28650, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 7, "title": '산부인과', "price": 34700, "category": '의료'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 7, "title": '산부인과', "price": 10500, "category": '의료'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 8, "title": '신선설렁탕', "price": 17000, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 9, "title": '산부인과', "price": 1300, "category": '의료'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 16, "title": '스타벅스', "price": 10000, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 16, "title": '핸드워시', "price": 19900, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 17, "title": '세탁소', "price": 6000, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 18, "title": '헤이그', "price": 35400, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 19, "title": '아웃백쿠폰', "price": 46450, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 19, "title": '테이블', "price": 19900, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 20, "title": '편의점', "price": 8200, "category": '식재료'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 23, "title": '굽네배달비', "price": 3000, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 24, "title": '마리떼', "price": 43100, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 28, "title": '베라 기프티콘', "price": 31000, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 2, "date": 28, "title": '논픽션 시향', "price": 2500, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 1, "title": '오빠네 떡볶이', "price": 12000, "category": '외식/배달'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 2, "title": '드라이시트', "price": 10500, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 2, "title": '나무수저', "price": 17370, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 4, "title": '준오헤어', "price": 36000, "category": '기타'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 5, "title": '에르메스', "price": 610000, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 6, "title": '골프장갑', "price": 26290, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 7, "title": '사이다', "price": 31200, "category": '식재료'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 8, "title": '다이소', "price": 1000, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 9, "title": '유명골프클럽', "price": 34000, "category": '기타'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 9, "title": '쓰레기봉지', "price": 5000, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 11, "title": '세탁소', "price": 15150, "category": '생필품'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 14, "title": '시에', "price": 119000, "category": '쇼핑'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 15, "title": '편의점', "price": 4500, "category": '식재료'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 22, "title": '판다', "price": 23500, "category": '약속'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 22, "title": '사진전', "price": 24000, "category": '약속'},
{"uuid": str(uuid.uuid4()), "instrument": 'hyundai', "month": 3, "date": 27, "title": '청기와타운', "price": 92000, "category": '외식/배달'},

{"uuid": str(uuid.uuid4()), "month":12, "date": 1, "title": "홍콩반점", "price": 22000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 6, "title": "버거킹", "price": 11700, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 6, "title": "주차비", "price": 6500, "category": "교통", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 8, "title": "헬로네이처", "price": 41580, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 8, "title": "엽떡", "price": 23000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 8, "title": "오목눈이", "price": 18600, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 9, "title": "넷플릭스", "price": 10150, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 13, "title": "편의점", "price": 12500, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 13, "title": "세탁소", "price": 6000, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 14, "title": "마라탕", "price": 39000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 20, "title": "가스비", "price": 58920, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 21, "title": "GS 슈퍼", "price": 2180, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 26, "title": "유튜브", "price": 6083, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 27, "title": "관리비", "price": 110860, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 2, "title": "굽네치킨", "price": 12000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 4, "title": "스시소라", "price": 160000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 7, "title": "이디야", "price": 11000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 8, "title": "골프장", "price": 28000, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 8, "title": "피스피스", "price": 26800, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 8, "title": "요물커피", "price": 10400, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 9, "title": "넷플릭스", "price": 10150, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 13, "title": "영양제", "price": 17400, "category": "의료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 15, "title": "닭갈비", "price": 75000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 15, "title": "카페", "price": 11500, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 15, "title": "렌즈", "price": 58000, "category": "생필품", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 16, "title": "요기패스", "price": 900, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 20, "title": "가스비", "price": 100820, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 25, "title": "관리비", "price": 111530, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 26, "title": "유튜브", "price": 6083, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 3, "title": "커피빈", "price": 10200, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 4, "title": "루루 보험", "price": 467590, "category": "가족행사", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 5, "title": "라티놀", "price": 21100, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 9, "title": "넷플릭스", "price": 11900, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 21, "title": "가스비", "price": 99580, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 22, "title": "관리비", "price": 130090, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 26, "title": "유튜브", "price": 6083, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 26, "title": "연회비", "price": 15000, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 1, "title": "요기패스", "price": 4400, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 6, "title": "이탈리안클럽", "price": 94000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 6, "title": "밀리토피아 골프", "price": 33000, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 6, "title": "컨플릭트 커피", "price": 13000, "category": "외식/배달", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 8, "title": "트랙패드", "price": 11470, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 9, "title": "넷플릭스", "price": 11900, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 18, "title": "세븐일레븐", "price": 6000, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 18, "title": "약국", "price": 3000, "category": "의료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 18, "title": "동사무소", "price": 600, "category": "기타", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 21, "title": "가스비", "price": 73300, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 22, "title": "신속항원", "price": 5000, "category": "의료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 25, "title": "관리비", "price": 133770, "category": "고지서", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 25, "title": "바닐라시럽", "price": 10000, "category": "식재료", "instrument": "woori"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 26, "title": "유튜브", "price": 6083, "category": "고지서", "instrument": "woori"},

{"uuid": str(uuid.uuid4()), "month":12, "date": 4, "title": "헬로네이처", "price": 25999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 5, "title": "요기요", "price": 12500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 6, "title": "로아르", "price": 61999, "category": "쇼핑", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 6, "title": "올리브영", "price": 37990, "category": "화장품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 9, "title": "마켓컬리", "price": 27999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 11, "title": "호빵", "price": 8999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 12, "title": "고트델리", "price": 36500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 12, "title": "마켓컬리", "price": 20980, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 15, "title": "카카오쇼핑", "price": 6900, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 16, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 17, "title": "배스킨라빈스", "price": 10999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 18, "title": "써브웨이", "price": 16999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 19, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 20, "title": "KFC", "price": 19500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 20, "title": "롯데시티호텔", "price": 39999, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 21, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 21, "title": "배민", "price": 10999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 22, "title": "유플러스", "price": 38243, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 23, "title": "헬로네이처", "price": 49999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 24, "title": "묵은지", "price": 7999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 25, "title": "돈까스", "price": 11520, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 25, "title": "커피빈", "price": 6100, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 25, "title": "아메리칸트레일러", "price": 5490, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 27, "title": "나무수저", "price": 9960, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 27, "title": "마스크", "price": 11999, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 28, "title": "세탁소", "price": 4800, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 28, "title": "디퓨저", "price": 15999, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 29, "title": "마켓컬리", "price": 13999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 30, "title": "후참", "price": 16500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":12, "date": 31, "title": "헬로네이처", "price": 40999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 1, "title": "김밥+라볶이", "price": 22800, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 4, "title": "오아시스", "price": 20999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 6, "title": "스팸", "price": 16999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 12, "title": "오목눈이", "price": 11300, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 12, "title": "헬로네이처", "price": 39999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 12, "title": "바이통타이", "price": 10700, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 12, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 14, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 15, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 16, "title": "배스킨라빈스", "price": 10400, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 16, "title": "김밥 라볶이", "price": 12600, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 16, "title": "립밤", "price": 7230, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 17, "title": "마켓컬리", "price": 20999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 17, "title": "버거킹", "price": 10999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 18, "title": "족발", "price": 26999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 18, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 19, "title": "자동차세", "price": 300545, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 19, "title": "헬로네이처", "price": 40999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 19, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 20, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 21, "title": "유플러스", "price": 20246, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 21, "title": "블랑오브", "price": 35800, "category": "쇼핑", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 21, "title": "마켓컬리", "price": 22810, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 22, "title": "파리바게뜨", "price": 7600, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 22, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 25, "title": "햇반", "price": 20720, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 26, "title": "UVO", "price": 1590, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 28, "title": "롯데리아", "price": 10700, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 30, "title": "피자", "price": 20410, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 31, "title": "굽네 쿠폰", "price": 7999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":1, "date": 31, "title": "서울페이", "price": 108000, "category": "가족행사", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 1, "title": "물", "price": 6900, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 1, "title": "식혜", "price": 7990, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 1, "title": "KFC", "price": 18500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 2, "title": "식자재마트", "price": 8780, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 5, "title": "헬로네이처", "price": 50999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 6, "title": "GS슈퍼", "price": 4950, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 6, "title": "편의점", "price": 12000, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 8, "title": "생리대", "price": 5930, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 9, "title": "헬로네이처", "price": 40999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 9, "title": "마스크", "price": 10900, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 10, "title": "라티놀", "price": 16600, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 11, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 12, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 13, "title": "죽", "price": 9999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 13, "title": "물", "price": 6900, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 13, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 14, "title": "배스킨라빈스", "price": 14500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 14, "title": "현미", "price": 10999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 16, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 16, "title": "오아시스", "price": 23999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 16, "title": "연두", "price": 6980, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 18, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 18, "title": "헬로네이처", "price": 42940, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 18, "title": "핸드폰케이스", "price": 10500, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 22, "title": "시스맥스 서랍", "price": 14999, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 23, "title": "유플러스", "price": 3416, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 23, "title": "마켓컬리", "price": 19999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 23, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 25, "title": "배스킨라빈스", "price": 7500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 25, "title": "요기패스", "price": 4900, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":2, "date": 28, "title": "유보", "price": 9900, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 1, "title": "GS슈퍼", "price": 9800, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 1, "title": "헬로네이쳐", "price": 40999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 3, "title": "고무장갑", "price": 11500, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 3, "title": "나이키", "price": 6999, "category": "쇼핑", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 7, "title": "맥도날드", "price": 12500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 8, "title": "카멜커피", "price": 5500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 9, "title": "홍콩반점", "price": 22900, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 11, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 11, "title": "크리넥스", "price": 8999, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 11, "title": "편의점", "price": 4400, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 12, "title": "버거킹", "price": 11999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 12, "title": "헬로네이처", "price": 37568, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 13, "title": "투썸", "price": 11200, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 14, "title": "컬리", "price": 19999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 15, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 15, "title": "뿌링클", "price": 13999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 16, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 19, "title": "피자", "price": 19999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 19, "title": "물", "price": 11900, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 19, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 20, "title": "라티놀", "price": 18500, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 21, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 22, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 22, "title": "라이크유 니트", "price": 39900, "category": "쇼핑", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 23, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 24, "title": "유플러스", "price": 14247, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 24, "title": "유플러스", "price": 5999, "category": "통신비", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 24, "title": "요기패스", "price": 4900, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 24, "title": "롯데리아", "price": 10999, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 26, "title": "식자재마트", "price": 26620, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 26, "title": "마스크", "price": 10999, "category": "생필품", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 28, "title": "유보", "price": 9900, "category": "기타", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 28, "title": "마켓컬리", "price": 20999, "category": "식재료", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 29, "title": "투썸", "price": 6400, "category": "외식/배달", "instrument": "shinhan"},
{"uuid": str(uuid.uuid4()), "month":3, "date": 29, "title": "유보", "price": 8940, "category": "기타", "instrument": "shinhan"}]


db = my_client['money']
collection = db['expense']

# collection.delete_all()

# collection.insert_many(hyundai)
# collection.insert_many(woori)
# collection.insert_many(shinhan)

# collection.insert_many(data)
collection.insert_many(april)

